/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as DisplayCodeRouteImport } from './routes/display.$code'
import { Route as SessionCodeRouteImport } from './routes/session.$code'
import { Route as AuthenticatedRoomsRoomIdRouteImport } from './routes/_authenticated/rooms.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DisplayCodeRoute = DisplayCodeRouteImport.update({
  id: '/display/$code',
  path: '/display/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCodeRoute = SessionCodeRouteImport.update({
  id: '/session/$code',
  path: '/session/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoomsRoomIdRoute =
  AuthenticatedRoomsRoomIdRouteImport.update({
    id: '/rooms/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check-email': typeof CheckEmailRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/display/$code': typeof DisplayCodeRoute
  '/session/$code': typeof SessionCodeRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check-email': typeof CheckEmailRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/display/$code': typeof DisplayCodeRoute
  '/session/$code': typeof SessionCodeRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/check-email': typeof CheckEmailRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/display/$code': typeof DisplayCodeRoute
  '/session/$code': typeof SessionCodeRoute
  '/_authenticated/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/check-email'
    | '/reset-password'
    | '/dashboard'
    | '/display/$code'
    | '/session/$code'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/check-email'
    | '/reset-password'
    | '/dashboard'
    | '/display/$code'
    | '/session/$code'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/check-email'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/display/$code'
    | '/session/$code'
    | '/_authenticated/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckEmailRoute: typeof CheckEmailRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DisplayCodeRoute: typeof DisplayCodeRoute
  SessionCodeRoute: typeof SessionCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/display/$code': {
      id: '/display/$code'
      path: '/display/$code'
      fullPath: '/display/$code'
      preLoaderRoute: typeof DisplayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$code': {
      id: '/session/$code'
      path: '/session/$code'
      fullPath: '/session/$code'
      preLoaderRoute: typeof SessionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rooms/$roomId': {
      id: '/_authenticated/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRoomsRoomIdRoute: typeof AuthenticatedRoomsRoomIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRoomsRoomIdRoute: AuthenticatedRoomsRoomIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckEmailRoute: CheckEmailRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DisplayCodeRoute: DisplayCodeRoute,
  SessionCodeRoute: SessionCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
